apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: kustomize-argocd-demo

resources:
  - ../../base

patches:
  - path: replica-patch.yaml

images:
  - name: shivawmm1810/weather-dashboard-app
    newTag: "03f883a1fa3a9dcf867547e683d976d6fd0fc6eb"