apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: kustomize-argocd-prod

resources:
  - ../../base

patches:
  - path: replica-patch.yaml
  - path: ingress-patch.yaml

images:
  - name: shivawmm1810/weather-dashboard-app
    newTag: latest